name: Publish Python distributions to PyPI

on:
  push:
    branches:
      - master

jobs:
  build-n-publish:
    if: github.repository_owner == 'dptech-corp'
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.9
      uses: actions/setup-python@master
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  send-email:
    if: github.repository_owner == 'dptech-corp'
    name: send email to inform developers
    runs-on: ubuntu-latest
    needs: [ build-n-publish ]
    steps:
    - name: read version
      id: read
      uses: juliangruber/read-file-action@v1
      with:
        path: ./VERSION
    - name: send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.feishu.cn
        server_port: 465
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: PyPI Auto Build For Dflow
        body: https://pypi.org/project/pydflow/${{ steps.read.outputs.content }}/
        to: ${{ secrets.MAIL_RECEIVER_LIST }}
        from: Github Actions
        content_type: text
